// PLACEHOLDER — generated by `pnpm supabase:types`. Committed so the project compiles
// before the first generation run. CI fails if this file diverges from the schema.
//
// Do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          bio: string | null;
          city: string | null;
          birthdate: string | null;
          age: number | null;
          gender: string | null;
          sexual_orientation: string | null;
          interested_in_seeing: string[] | null;
          occupation: string | null;
          education: string | null;
          hometown: string | null;
          height: number | null;
          show_occupation: boolean;
          show_education: boolean;
          show_city: boolean;
          show_hometown: boolean;
          show_height: boolean;
          onboarding_complete: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string; display_name: string };
        Update: Partial<Database['public']['Tables']['profiles']['Row']>;
      };
      profile_photos: {
        Row: {
          id: string;
          user_id: string;
          slot_index: number;
          storage_path: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['profile_photos']['Row'], 'id' | 'created_at'> & {
          id?: string;
          created_at?: string;
        };
        Update: Partial<Database['public']['Tables']['profile_photos']['Row']>;
      };
      profile_likes: {
        Row: {
          liker_id: string;
          liked_id: string;
          created_at: string;
        };
        Insert: { liker_id: string; liked_id: string; created_at?: string };
        Update: Partial<{ liker_id: string; liked_id: string; created_at: string }>;
      };
      matches: {
        Row: {
          id: string;
          user_low_id: string;
          user_high_id: string;
          created_at: string;
        };
        Insert: { user_low_id: string; user_high_id: string; id?: string; created_at?: string };
        Update: Partial<Database['public']['Tables']['matches']['Row']>;
      };
      chat_rooms: {
        Row: { id: string; match_id: string; created_at: string };
        Insert: { match_id: string; id?: string; created_at?: string };
        Update: Partial<Database['public']['Tables']['chat_rooms']['Row']>;
      };
      chat_room_members: {
        Row: { room_id: string; user_id: string; joined_at: string };
        Insert: { room_id: string; user_id: string; joined_at?: string };
        Update: Partial<Database['public']['Tables']['chat_room_members']['Row']>;
      };
      chat_messages: {
        Row: {
          id: string;
          room_id: string;
          sender_id: string;
          body: string;
          created_at: string;
        };
        Insert: { room_id: string; sender_id: string; body: string; id?: string; created_at?: string };
        Update: Partial<Database['public']['Tables']['chat_messages']['Row']>;
      };
      chat_receipts: {
        Row: { message_id: string; reader_id: string; read_at: string };
        Insert: { message_id: string; reader_id: string; read_at?: string };
        Update: Partial<Database['public']['Tables']['chat_receipts']['Row']>;
      };
      business_promotions: {
        Row: {
          id: string;
          business_name: string;
          category: string;
          description: string | null;
          address: string | null;
          latitude: number;
          longitude: number;
          starts_at: string | null;
          ends_at: string | null;
          is_active: boolean;
          max_claims: number;
          created_by: string;
          created_at: string;
        };
        Insert: Partial<Database['public']['Tables']['business_promotions']['Row']> & {
          business_name: string;
          category: string;
          latitude: number;
          longitude: number;
          created_by: string;
        };
        Update: Partial<Database['public']['Tables']['business_promotions']['Row']>;
      };
      promotion_tickets: {
        Row: {
          id: string;
          promotion_id: string;
          user_id: string;
          claimed_at: string;
          claimed_on: string;
        };
        Insert: { promotion_id: string; user_id: string; id?: string; claimed_at?: string; claimed_on?: string };
        Update: Partial<Database['public']['Tables']['promotion_tickets']['Row']>;
      };
      push_tokens: {
        Row: { user_id: string; token: string; platform: 'ios'; last_seen: string };
        Insert: { user_id: string; token: string; platform?: 'ios'; last_seen?: string };
        Update: Partial<Database['public']['Tables']['push_tokens']['Row']>;
      };
    };
    Functions: {
      get_or_create_match_chat: { Args: { p_match_id: string }; Returns: string };
      get_promotion_availability: {
        Args: { p_promotion_id: string };
        Returns: { max_claims: number; claimed_count: number; remaining_count: number; already_claimed: boolean };
      };
      claim_promotion_ticket: {
        Args: { p_promotion_id: string };
        Returns: { ticket_id: string; remaining_count: number };
      };
      get_missed_connections: {
        Args: { p_limit: number; p_after: string | null };
        Returns: ReadonlyArray<{
          other_user_id: string;
          display_name: string;
          age: number | null;
          photo_storage_path: string | null;
          promotion_id: string;
          business_name: string;
          category: string;
          description: string | null;
          claimed_on: string;
          claimed_at: string;
        }>;
      };
      has_missed_connection: { Args: { p_other_user_id: string }; Returns: boolean };
    };
    Enums: Record<string, never>;
  };
};
